version: '3.7'
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    image: book_store
    volumes:
      - .:/opt/app
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  postgres:
